version: '3.9'

services:
  backend:
    container_name: 'weather-backend'
    image: weather-backend
    build: ./backend
    restart: always
    ports:
      - '9000:9000'
  frontend:
    container_name: 'weather-frontend'
    image: weather-frontend
    build: ./frontendapp
    restart: always
    ports:
      - '3000:3000'